### ISSUE TITLE
The symbols font name should be cased consistently

### ISSUE THREAD

**Issue by prichey** [40Digits/gulp-starter#8]
In the gulp config.js settings for the symbols task, `fontName` is defined as `'Symbols'`, which breaks because it is included as `src: url('assets/fonts/symbols/symbols.eot');` etc. in `helpers/_symbols.scss`.

 For some reason it works locally but breaks on the server. I personally feel that the font name should be made to be lower case, but either way it should be named consistently.

**Comment by besimhu** [comment]
Fixed
